### ISSUE TITLE
Force tare issue with WSG50 gripper

### ISSUE THREAD

**Issue by radhen** [nalt/wsg50-ros-pkg#5]
I have a WSG50 Weiss gripper. I am using this package and I keep getting this error

doTare()	Command TARE not successful: Service or data is not available

I do not have any fingers connected to the gripper which might be the reason in my opinion. Can anyone suggest a work around this? I have plans on connecting my custom made fingers to the gripper afterwards once I get the driver working.

**Comment by nalt** [comment]
Yes, it's command 0x38, which is for the fingers. The message should not disturb, but of course you can comment out the call to doTare().
